#############################################################################
# Makefile for building: gecko
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  gecko.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile gecko.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -pthread -std=c++20 -m64 -I/snap/root-framework/943/usr/local/include -O2 -g -march=native -ggdb -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -Ilib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gecko1.0.0
DISTDIR = /home/denis/IFIN_practica/gecko-light/.tmp/gecko1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -g -L/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -l_sis3100 -lgsl -lgslcblas -lusb -lboost_filesystem -lboost_system -L/snap/root-framework/943/usr/local/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lROOTVecOps -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -Wl,-rpath,/snap/root-framework/943/usr/local/lib -pthread -lm -ldl -rdynamic -lpthread /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = core/2Ddisplay.cpp \
		core/baseplugin.cpp \
		core/eventbuffer.cpp \
		core/geckoremote.cpp \
		core/interfacemanager.cpp \
		core/main.cpp \
		core/modulemanager.cpp \
		core/outputplugin.cpp \
		core/plot2d.cpp \
		core/pluginconnector.cpp \
		core/pluginmanager.cpp \
		core/pluginthread.cpp \
		core/remotecontrolpanel.cpp \
		core/runmanager.cpp \
		core/runthread.cpp \
		core/scopemainwindow.cpp \
		core/threadbuffer.cpp \
		core/viewport.cpp \
		interface/sis3100module.cpp \
		interface/sis3100ui.cpp \
		module/caen792module.cpp \
		module/caen792ui.cpp \
		module/caenadcdmx.cpp \
		plugin/aux/fanoutplugin.cpp \
		plugin/aux/inttodoubleplugin.cpp \
		plugin/aux/pulsing.cpp \
		plugin/cache/multiplecachehistogramplugin.cpp \
		plugin/pack/eventbuilderBIGROOTplugin.cpp \
		plugin/pack/eventbuilderBIGplugin.cpp \
		plugin/processing/mtdc32Processor.cpp \
		plugin/processing/madc32Processor.cpp \
		module/mesytecMadc32ui.cpp \
		module/mesytecMadc32module.cpp \
		module/mesytecMadc32dmx.cpp \
		module/mesytecMtdc32ui.cpp \
		module/mesytecMtdc32module.cpp \
		module/mesytecMtdc32dmx.cpp \
		plugin/cache/MatrixPlotWalk.cpp moc_addeditdlgs.cpp \
		moc_geckoremote.cpp \
		moc_pluginthread.cpp \
		moc_remotecontrolpanel.cpp \
		moc_runthread.cpp \
		moc_scopemainwindow.cpp \
		moc_systeminfo.cpp \
		moc_threadbuffer.cpp \
		moc_abstractmodule.cpp \
		moc_abstractplugin.cpp \
		moc_basemodule.cpp \
		moc_baseplugin.cpp \
		moc_geckoui.cpp \
		moc_interfacemanager.cpp \
		moc_modulemanager.cpp \
		moc_outputplugin.cpp \
		moc_plot2d.cpp \
		moc_pluginmanager.cpp \
		moc_runmanager.cpp \
		moc_sis3100module.cpp \
		moc_sis3100ui.cpp \
		moc_caen792module.cpp \
		moc_caen792ui.cpp \
		moc_inttodoubleplugin.cpp \
		moc_pulsing.cpp \
		moc_multiplecachehistogramplugin.cpp \
		moc_eventbuilderBIGROOTplugin.cpp \
		moc_eventbuilderBIGplugin.cpp \
		moc_mtdc32Processor.cpp \
		moc_madc32Processor.cpp \
		moc_mesytecMadc32module.cpp \
		moc_mesytecMadc32ui.cpp \
		moc_mesytecMtdc32module.cpp \
		moc_mesytecMtdc32ui.cpp \
		moc_MatrixPlotWalk.cpp
OBJECTS       = 2Ddisplay.o \
		baseplugin.o \
		eventbuffer.o \
		geckoremote.o \
		interfacemanager.o \
		main.o \
		modulemanager.o \
		outputplugin.o \
		plot2d.o \
		pluginconnector.o \
		pluginmanager.o \
		pluginthread.o \
		remotecontrolpanel.o \
		runmanager.o \
		runthread.o \
		scopemainwindow.o \
		threadbuffer.o \
		viewport.o \
		sis3100module.o \
		sis3100ui.o \
		caen792module.o \
		caen792ui.o \
		caenadcdmx.o \
		fanoutplugin.o \
		inttodoubleplugin.o \
		pulsing.o \
		multiplecachehistogramplugin.o \
		eventbuilderBIGROOTplugin.o \
		eventbuilderBIGplugin.o \
		mtdc32Processor.o \
		madc32Processor.o \
		mesytecMadc32ui.o \
		mesytecMadc32module.o \
		mesytecMadc32dmx.o \
		mesytecMtdc32ui.o \
		mesytecMtdc32module.o \
		mesytecMtdc32dmx.o \
		MatrixPlotWalk.o \
		moc_addeditdlgs.o \
		moc_geckoremote.o \
		moc_pluginthread.o \
		moc_remotecontrolpanel.o \
		moc_runthread.o \
		moc_scopemainwindow.o \
		moc_systeminfo.o \
		moc_threadbuffer.o \
		moc_abstractmodule.o \
		moc_abstractplugin.o \
		moc_basemodule.o \
		moc_baseplugin.o \
		moc_geckoui.o \
		moc_interfacemanager.o \
		moc_modulemanager.o \
		moc_outputplugin.o \
		moc_plot2d.o \
		moc_pluginmanager.o \
		moc_runmanager.o \
		moc_sis3100module.o \
		moc_sis3100ui.o \
		moc_caen792module.o \
		moc_caen792ui.o \
		moc_inttodoubleplugin.o \
		moc_pulsing.o \
		moc_multiplecachehistogramplugin.o \
		moc_eventbuilderBIGROOTplugin.o \
		moc_eventbuilderBIGplugin.o \
		moc_mtdc32Processor.o \
		moc_madc32Processor.o \
		moc_mesytecMadc32module.o \
		moc_mesytecMadc32ui.o \
		moc_mesytecMtdc32module.o \
		moc_mesytecMtdc32ui.o \
		moc_MatrixPlotWalk.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gecko.pro include/2Ddisplay.h \
		include/addeditdlgs.h \
		include/geckoremote.h \
		include/pluginthread.h \
		include/remotecontrolpanel.h \
		include/runthread.h \
		include/scopemainwindow.h \
		include/systeminfo.h \
		include/threadbuffer.h \
		include/abstractinterface.h \
		include/abstractmodule.h \
		include/abstractplugin.h \
		include/baseinterface.h \
		include/basemodule.h \
		include/baseplugin.h \
		include/baseui.h \
		include/confmap.h \
		include/eventbuffer.h \
		include/geckoui.h \
		include/hexspinbox.h \
		include/interfacemanager.h \
		include/modulemanager.h \
		include/outputplugin.h \
		include/plot2d.h \
		include/pluginconnector.h \
		include/pluginconnectorplain.h \
		include/pluginconnectorqueued.h \
		include/pluginmanager.h \
		include/runmanager.h \
		include/samdsp.h \
		include/samqvector.h \
		include/viewport.h \
		interface/sis3100module.h \
		interface/sis3100ui.h \
		module/caen792module.h \
		module/caen792ui.h \
		module/caenadcdmx.h \
		module/caen_v785.h \
		module/caen_v792.h \
		plugin/aux/fanoutplugin.h \
		plugin/aux/inttodoubleplugin.h \
		plugin/aux/pulsing.h \
		plugin/cache/multiplecachehistogramplugin.h \
		plugin/pack/eventbuilderBIGROOTplugin.h \
		plugin/pack/eventbuilderBIGplugin.h \
		plugin/processing/mtdc32Processor.h \
		plugin/processing/madc32Processor.h \
		module/mesytec_madc_32_v2.h \
		module/mesytecMadc32module.h \
		module/mesytecMadc32dmx.h \
		module/mesytecMadc32ui.h \
		module/mesytec_mtdc_32_v2.h \
		module/mesytecMtdc32module.h \
		module/mesytecMtdc32dmx.h \
		module/mesytecMtdc32ui.h \
		plugin/cache/MatrixPlotWalk.h core/2Ddisplay.cpp \
		core/baseplugin.cpp \
		core/eventbuffer.cpp \
		core/geckoremote.cpp \
		core/interfacemanager.cpp \
		core/main.cpp \
		core/modulemanager.cpp \
		core/outputplugin.cpp \
		core/plot2d.cpp \
		core/pluginconnector.cpp \
		core/pluginmanager.cpp \
		core/pluginthread.cpp \
		core/remotecontrolpanel.cpp \
		core/runmanager.cpp \
		core/runthread.cpp \
		core/scopemainwindow.cpp \
		core/threadbuffer.cpp \
		core/viewport.cpp \
		interface/sis3100module.cpp \
		interface/sis3100ui.cpp \
		module/caen792module.cpp \
		module/caen792ui.cpp \
		module/caenadcdmx.cpp \
		plugin/aux/fanoutplugin.cpp \
		plugin/aux/inttodoubleplugin.cpp \
		plugin/aux/pulsing.cpp \
		plugin/cache/multiplecachehistogramplugin.cpp \
		plugin/pack/eventbuilderBIGROOTplugin.cpp \
		plugin/pack/eventbuilderBIGplugin.cpp \
		plugin/processing/mtdc32Processor.cpp \
		plugin/processing/madc32Processor.cpp \
		module/mesytecMadc32ui.cpp \
		module/mesytecMadc32module.cpp \
		module/mesytecMadc32dmx.cpp \
		module/mesytecMtdc32ui.cpp \
		module/mesytecMtdc32module.cpp \
		module/mesytecMtdc32dmx.cpp \
		plugin/cache/MatrixPlotWalk.cpp
QMAKE_TARGET  = gecko
DESTDIR       = 
TARGET        = gecko


first: all
####### Build rules

gecko:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gecko.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gecko.pro
	$(QMAKE) -o Makefile gecko.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
gecko.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile gecko.pro

qmake_all: FORCE


all: Makefile gecko

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/2Ddisplay.h include/addeditdlgs.h include/geckoremote.h include/pluginthread.h include/remotecontrolpanel.h include/runthread.h include/scopemainwindow.h include/systeminfo.h include/threadbuffer.h include/abstractinterface.h include/abstractmodule.h include/abstractplugin.h include/baseinterface.h include/basemodule.h include/baseplugin.h include/baseui.h include/confmap.h include/eventbuffer.h include/geckoui.h include/hexspinbox.h include/interfacemanager.h include/modulemanager.h include/outputplugin.h include/plot2d.h include/pluginconnector.h include/pluginconnectorplain.h include/pluginconnectorqueued.h include/pluginmanager.h include/runmanager.h include/samdsp.h include/samqvector.h include/viewport.h interface/sis3100module.h interface/sis3100ui.h module/caen792module.h module/caen792ui.h module/caenadcdmx.h module/caen_v785.h module/caen_v792.h plugin/aux/fanoutplugin.h plugin/aux/inttodoubleplugin.h plugin/aux/pulsing.h plugin/cache/multiplecachehistogramplugin.h plugin/pack/eventbuilderBIGROOTplugin.h plugin/pack/eventbuilderBIGplugin.h plugin/processing/mtdc32Processor.h plugin/processing/madc32Processor.h module/mesytec_madc_32_v2.h module/mesytecMadc32module.h module/mesytecMadc32dmx.h module/mesytecMadc32ui.h module/mesytec_mtdc_32_v2.h module/mesytecMtdc32module.h module/mesytecMtdc32dmx.h module/mesytecMtdc32ui.h plugin/cache/MatrixPlotWalk.h $(DISTDIR)/
	$(COPY_FILE) --parents core/2Ddisplay.cpp core/baseplugin.cpp core/eventbuffer.cpp core/geckoremote.cpp core/interfacemanager.cpp core/main.cpp core/modulemanager.cpp core/outputplugin.cpp core/plot2d.cpp core/pluginconnector.cpp core/pluginmanager.cpp core/pluginthread.cpp core/remotecontrolpanel.cpp core/runmanager.cpp core/runthread.cpp core/scopemainwindow.cpp core/threadbuffer.cpp core/viewport.cpp interface/sis3100module.cpp interface/sis3100ui.cpp module/caen792module.cpp module/caen792ui.cpp module/caenadcdmx.cpp plugin/aux/fanoutplugin.cpp plugin/aux/inttodoubleplugin.cpp plugin/aux/pulsing.cpp plugin/cache/multiplecachehistogramplugin.cpp plugin/pack/eventbuilderBIGROOTplugin.cpp plugin/pack/eventbuilderBIGplugin.cpp plugin/processing/mtdc32Processor.cpp plugin/processing/madc32Processor.cpp module/mesytecMadc32ui.cpp module/mesytecMadc32module.cpp module/mesytecMadc32dmx.cpp module/mesytecMtdc32ui.cpp module/mesytecMtdc32module.cpp module/mesytecMtdc32dmx.cpp plugin/cache/MatrixPlotWalk.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -pthread -std=c++20 -m64 -I/snap/root-framework/943/usr/local/include -O2 -g -march=native -ggdb -D_REENTRANT -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_addeditdlgs.cpp moc_geckoremote.cpp moc_pluginthread.cpp moc_remotecontrolpanel.cpp moc_runthread.cpp moc_scopemainwindow.cpp moc_systeminfo.cpp moc_threadbuffer.cpp moc_abstractmodule.cpp moc_abstractplugin.cpp moc_basemodule.cpp moc_baseplugin.cpp moc_geckoui.cpp moc_interfacemanager.cpp moc_modulemanager.cpp moc_outputplugin.cpp moc_plot2d.cpp moc_pluginmanager.cpp moc_runmanager.cpp moc_sis3100module.cpp moc_sis3100ui.cpp moc_caen792module.cpp moc_caen792ui.cpp moc_inttodoubleplugin.cpp moc_pulsing.cpp moc_multiplecachehistogramplugin.cpp moc_eventbuilderBIGROOTplugin.cpp moc_eventbuilderBIGplugin.cpp moc_mtdc32Processor.cpp moc_madc32Processor.cpp moc_mesytecMadc32module.cpp moc_mesytecMadc32ui.cpp moc_mesytecMtdc32module.cpp moc_mesytecMtdc32ui.cpp moc_MatrixPlotWalk.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_addeditdlgs.cpp moc_geckoremote.cpp moc_pluginthread.cpp moc_remotecontrolpanel.cpp moc_runthread.cpp moc_scopemainwindow.cpp moc_systeminfo.cpp moc_threadbuffer.cpp moc_abstractmodule.cpp moc_abstractplugin.cpp moc_basemodule.cpp moc_baseplugin.cpp moc_geckoui.cpp moc_interfacemanager.cpp moc_modulemanager.cpp moc_outputplugin.cpp moc_plot2d.cpp moc_pluginmanager.cpp moc_runmanager.cpp moc_sis3100module.cpp moc_sis3100ui.cpp moc_caen792module.cpp moc_caen792ui.cpp moc_inttodoubleplugin.cpp moc_pulsing.cpp moc_multiplecachehistogramplugin.cpp moc_eventbuilderBIGROOTplugin.cpp moc_eventbuilderBIGplugin.cpp moc_mtdc32Processor.cpp moc_madc32Processor.cpp moc_mesytecMadc32module.cpp moc_mesytecMadc32ui.cpp moc_mesytecMtdc32module.cpp moc_mesytecMtdc32ui.cpp moc_MatrixPlotWalk.cpp
moc_addeditdlgs.cpp: include/addeditdlgs.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/modulemanager.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/interfacemanager.h \
		include/hexspinbox.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/addeditdlgs.h -o moc_addeditdlgs.cpp

moc_geckoremote.cpp: include/geckoremote.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/geckoremote.h -o moc_geckoremote.cpp

moc_pluginthread.cpp: include/pluginthread.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/pluginthread.h -o moc_pluginthread.cpp

moc_remotecontrolpanel.cpp: include/remotecontrolpanel.h \
		include/geckoremote.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/remotecontrolpanel.h -o moc_remotecontrolpanel.cpp

moc_runthread.cpp: include/runthread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/runthread.h -o moc_runthread.cpp

moc_scopemainwindow.cpp: include/scopemainwindow.h \
		include/runthread.h \
		include/pluginthread.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/abstractinterface.h \
		include/geckoremote.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/scopemainwindow.h -o moc_scopemainwindow.cpp

moc_systeminfo.cpp: include/systeminfo.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/systeminfo.h -o moc_systeminfo.cpp

moc_threadbuffer.cpp: include/threadbuffer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/threadbuffer.h -o moc_threadbuffer.cpp

moc_abstractmodule.cpp: include/abstractmodule.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/abstractmodule.h -o moc_abstractmodule.cpp

moc_abstractplugin.cpp: include/abstractplugin.h \
		include/pluginconnector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/abstractplugin.h -o moc_abstractplugin.cpp

moc_basemodule.cpp: include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/basemodule.h -o moc_basemodule.cpp

moc_baseplugin.cpp: include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/baseplugin.h -o moc_baseplugin.cpp

moc_geckoui.cpp: include/geckoui.h \
		include/hexspinbox.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/geckoui.h -o moc_geckoui.cpp

moc_interfacemanager.cpp: include/interfacemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/interfacemanager.h -o moc_interfacemanager.cpp

moc_modulemanager.cpp: include/modulemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/modulemanager.h -o moc_modulemanager.cpp

moc_outputplugin.cpp: include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/outputplugin.h -o moc_outputplugin.cpp

moc_plot2d.cpp: include/plot2d.h \
		include/samdsp.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/plot2d.h -o moc_plot2d.cpp

moc_pluginmanager.cpp: include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/pluginmanager.h -o moc_pluginmanager.cpp

moc_runmanager.cpp: include/runmanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/runmanager.h -o moc_runmanager.cpp

moc_sis3100module.cpp: interface/sis3100module.h \
		lib/sis3100_calls/sis3100_vme_calls.h \
		include/baseinterface.h \
		include/abstractinterface.h \
		interface/sis3100ui.h \
		interface/sis3100module.h \
		include/baseui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interface/sis3100module.h -o moc_sis3100module.cpp

moc_sis3100ui.cpp: interface/sis3100ui.h \
		interface/sis3100module.h \
		lib/sis3100_calls/sis3100_vme_calls.h \
		include/baseinterface.h \
		include/abstractinterface.h \
		interface/sis3100ui.h \
		include/baseui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include interface/sis3100ui.h -o moc_sis3100ui.cpp

moc_caen792module.cpp: module/caen792module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/caenadcdmx.h \
		module/caen_v785.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include module/caen792module.h -o moc_caen792module.cpp

moc_caen792ui.cpp: module/caen792ui.h \
		include/hexspinbox.h \
		include/baseui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include module/caen792ui.h -o moc_caen792ui.cpp

moc_inttodoubleplugin.cpp: plugin/aux/inttodoubleplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/aux/inttodoubleplugin.h -o moc_inttodoubleplugin.cpp

moc_pulsing.cpp: plugin/aux/pulsing.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/abstractinterface.h \
		include/abstractmodule.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/aux/pulsing.h -o moc_pulsing.cpp

moc_multiplecachehistogramplugin.cpp: plugin/cache/multiplecachehistogramplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginconnectorqueued.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/plot2d.h \
		include/samdsp.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/cache/multiplecachehistogramplugin.h -o moc_multiplecachehistogramplugin.cpp

moc_eventbuilderBIGROOTplugin.cpp: plugin/pack/eventbuilderBIGROOTplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/pluginmanager.h \
		include/pluginconnectorqueued.h \
		/snap/root-framework/943/usr/local/include/TFile.h \
		/snap/root-framework/943/usr/local/include/Compression.h \
		/snap/root-framework/943/usr/local/include/RtypesCore.h \
		/snap/root-framework/943/usr/local/include/ROOT/RConfig.hxx \
		/snap/root-framework/943/usr/local/include/RVersion.h \
		/snap/root-framework/943/usr/local/include/ROOT/RVersion.hxx \
		/snap/root-framework/943/usr/local/include/RConfigure.h \
		/snap/root-framework/943/usr/local/include/DllImport.h \
		/snap/root-framework/943/usr/local/include/TDirectoryFile.h \
		/snap/root-framework/943/usr/local/include/TDirectory.h \
		/snap/root-framework/943/usr/local/include/TNamed.h \
		/snap/root-framework/943/usr/local/include/TObject.h \
		/snap/root-framework/943/usr/local/include/Rtypes.h \
		/snap/root-framework/943/usr/local/include/strtok.h \
		/snap/root-framework/943/usr/local/include/strlcpy.h \
		/snap/root-framework/943/usr/local/include/snprintf.h \
		/snap/root-framework/943/usr/local/include/TGenericClassInfo.h \
		/snap/root-framework/943/usr/local/include/TSchemaHelper.h \
		/snap/root-framework/943/usr/local/include/TIsAProxy.h \
		/snap/root-framework/943/usr/local/include/TVirtualIsAProxy.h \
		/snap/root-framework/943/usr/local/include/TStorage.h \
		/snap/root-framework/943/usr/local/include/TVersionCheck.h \
		/snap/root-framework/943/usr/local/include/TString.h \
		/snap/root-framework/943/usr/local/include/TMathBase.h \
		/snap/root-framework/943/usr/local/include/ROOT/TypeTraits.hxx \
		/snap/root-framework/943/usr/local/include/TClass.h \
		/snap/root-framework/943/usr/local/include/TDictionary.h \
		/snap/root-framework/943/usr/local/include/ESTLType.h \
		/snap/root-framework/943/usr/local/include/TObjArray.h \
		/snap/root-framework/943/usr/local/include/TSeqCollection.h \
		/snap/root-framework/943/usr/local/include/TCollection.h \
		/snap/root-framework/943/usr/local/include/TIterator.h \
		/snap/root-framework/943/usr/local/include/TVirtualRWMutex.h \
		/snap/root-framework/943/usr/local/include/TVirtualMutex.h \
		/snap/root-framework/943/usr/local/include/ROOT/RRangeCast.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/RSpan.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/span.hxx \
		/snap/root-framework/943/usr/local/include/TUUID.h \
		/snap/root-framework/943/usr/local/include/TList.h \
		/snap/root-framework/943/usr/local/include/TBuffer.h \
		/snap/root-framework/943/usr/local/include/TDataType.h \
		/snap/root-framework/943/usr/local/include/Bytes.h \
		/snap/root-framework/943/usr/local/include/Byteswap.h \
		/snap/root-framework/943/usr/local/include/TDatime.h \
		/snap/root-framework/943/usr/local/include/TUrl.h \
		/snap/root-framework/943/usr/local/include/ROOT/RConcurrentHashColl.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/TRWSpinLock.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/TSpinMutex.hxx \
		/snap/root-framework/943/usr/local/include/TTree.h \
		/snap/root-framework/943/usr/local/include/ROOT/TIOFeatures.hxx \
		/snap/root-framework/943/usr/local/include/TArrayD.h \
		/snap/root-framework/943/usr/local/include/TArray.h \
		/snap/root-framework/943/usr/local/include/TArrayI.h \
		/snap/root-framework/943/usr/local/include/TAttFill.h \
		/snap/root-framework/943/usr/local/include/TAttLine.h \
		/snap/root-framework/943/usr/local/include/TAttMarker.h \
		/snap/root-framework/943/usr/local/include/TVirtualTreePlayer.h \
		/snap/root-framework/943/usr/local/include/TBranch.h \
		/snap/root-framework/943/usr/local/include/TBranchCacheInfo.h \
		/snap/root-framework/943/usr/local/include/TBits.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/pack/eventbuilderBIGROOTplugin.h -o moc_eventbuilderBIGROOTplugin.cpp

moc_eventbuilderBIGplugin.cpp: plugin/pack/eventbuilderBIGplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/pluginmanager.h \
		include/pluginconnectorqueued.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/pack/eventbuilderBIGplugin.h -o moc_eventbuilderBIGplugin.cpp

moc_mtdc32Processor.cpp: plugin/processing/mtdc32Processor.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		module/mesytec_mtdc_32_v2.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/processing/mtdc32Processor.h -o moc_mtdc32Processor.cpp

moc_madc32Processor.cpp: plugin/processing/madc32Processor.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		module/mesytec_madc_32_v2.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/processing/madc32Processor.h -o moc_madc32Processor.cpp

moc_mesytecMadc32module.cpp: module/mesytecMadc32module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/mesytecMadc32dmx.h \
		module/mesytec_madc_32_v2.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include module/mesytecMadc32module.h -o moc_mesytecMadc32module.cpp

moc_mesytecMadc32ui.cpp: module/mesytecMadc32ui.h \
		include/plot2d.h \
		include/samdsp.h \
		include/hexspinbox.h \
		include/geckoui.h \
		module/mesytec_madc_32_v2.h \
		include/baseui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include module/mesytecMadc32ui.h -o moc_mesytecMadc32ui.cpp

moc_mesytecMtdc32module.cpp: module/mesytecMtdc32module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/mesytecMtdc32dmx.h \
		module/mesytec_mtdc_32_v2.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include module/mesytecMtdc32module.h -o moc_mesytecMtdc32module.cpp

moc_mesytecMtdc32ui.cpp: module/mesytecMtdc32ui.h \
		include/plot2d.h \
		include/samdsp.h \
		include/hexspinbox.h \
		include/geckoui.h \
		module/mesytec_mtdc_32_v2.h \
		include/baseui.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include module/mesytecMtdc32ui.h -o moc_mesytecMtdc32ui.cpp

moc_MatrixPlotWalk.cpp: plugin/cache/MatrixPlotWalk.h \
		include/2Ddisplay.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/pluginconnectorqueued.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/denis/IFIN_practica/gecko-light/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/denis/IFIN_practica/gecko-light -I/home/denis/IFIN_practica/gecko-light/include -I/home/denis/IFIN_practica/gecko-light/lib/sis3100_calls -I/snap/root-framework/943/usr/local/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include plugin/cache/MatrixPlotWalk.h -o moc_MatrixPlotWalk.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

2Ddisplay.o: core/2Ddisplay.cpp include/2Ddisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o 2Ddisplay.o core/2Ddisplay.cpp

baseplugin.o: core/baseplugin.cpp include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/abstractmodule.h \
		include/outputplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o baseplugin.o core/baseplugin.cpp

eventbuffer.o: core/eventbuffer.cpp include/eventbuffer.h \
		include/pluginconnector.h \
		include/threadbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventbuffer.o core/eventbuffer.cpp

geckoremote.o: core/geckoremote.cpp include/geckoremote.h \
		include/runmanager.h \
		include/systeminfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geckoremote.o core/geckoremote.cpp

interfacemanager.o: core/interfacemanager.cpp include/interfacemanager.h \
		include/abstractinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interfacemanager.o core/interfacemanager.cpp

main.o: core/main.cpp include/scopemainwindow.h \
		include/runthread.h \
		include/pluginthread.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/abstractinterface.h \
		include/geckoremote.h \
		/snap/root-framework/943/usr/local/include/TROOT.h \
		/snap/root-framework/943/usr/local/include/TDirectory.h \
		/snap/root-framework/943/usr/local/include/TNamed.h \
		/snap/root-framework/943/usr/local/include/TObject.h \
		/snap/root-framework/943/usr/local/include/Rtypes.h \
		/snap/root-framework/943/usr/local/include/RtypesCore.h \
		/snap/root-framework/943/usr/local/include/ROOT/RConfig.hxx \
		/snap/root-framework/943/usr/local/include/RVersion.h \
		/snap/root-framework/943/usr/local/include/ROOT/RVersion.hxx \
		/snap/root-framework/943/usr/local/include/RConfigure.h \
		/snap/root-framework/943/usr/local/include/DllImport.h \
		/snap/root-framework/943/usr/local/include/strtok.h \
		/snap/root-framework/943/usr/local/include/strlcpy.h \
		/snap/root-framework/943/usr/local/include/snprintf.h \
		/snap/root-framework/943/usr/local/include/TGenericClassInfo.h \
		/snap/root-framework/943/usr/local/include/TSchemaHelper.h \
		/snap/root-framework/943/usr/local/include/TIsAProxy.h \
		/snap/root-framework/943/usr/local/include/TVirtualIsAProxy.h \
		/snap/root-framework/943/usr/local/include/TStorage.h \
		/snap/root-framework/943/usr/local/include/TVersionCheck.h \
		/snap/root-framework/943/usr/local/include/TString.h \
		/snap/root-framework/943/usr/local/include/TMathBase.h \
		/snap/root-framework/943/usr/local/include/ROOT/TypeTraits.hxx \
		/snap/root-framework/943/usr/local/include/TClass.h \
		/snap/root-framework/943/usr/local/include/TDictionary.h \
		/snap/root-framework/943/usr/local/include/ESTLType.h \
		/snap/root-framework/943/usr/local/include/TObjArray.h \
		/snap/root-framework/943/usr/local/include/TSeqCollection.h \
		/snap/root-framework/943/usr/local/include/TCollection.h \
		/snap/root-framework/943/usr/local/include/TIterator.h \
		/snap/root-framework/943/usr/local/include/TVirtualRWMutex.h \
		/snap/root-framework/943/usr/local/include/TVirtualMutex.h \
		/snap/root-framework/943/usr/local/include/ROOT/RRangeCast.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/RSpan.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/span.hxx \
		/snap/root-framework/943/usr/local/include/TUUID.h \
		/snap/root-framework/943/usr/local/include/TList.h \
		/snap/root-framework/943/usr/local/include/TBuffer.h \
		/snap/root-framework/943/usr/local/include/TDataType.h \
		/snap/root-framework/943/usr/local/include/Bytes.h \
		/snap/root-framework/943/usr/local/include/Byteswap.h \
		/snap/root-framework/943/usr/local/include/TApplication.h \
		/snap/root-framework/943/usr/local/include/TQObject.h \
		/snap/root-framework/943/usr/local/include/TVirtualQConnection.h \
		/snap/root-framework/943/usr/local/include/TInterpreter.h \
		/snap/root-framework/943/usr/local/include/TInterpreterValue.h \
		/snap/root-framework/943/usr/local/include/TQClass.h \
		/snap/root-framework/943/usr/local/include/TApplicationImp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o core/main.cpp

modulemanager.o: core/modulemanager.cpp include/modulemanager.h \
		include/abstractmodule.h \
		include/threadbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulemanager.o core/modulemanager.cpp

outputplugin.o: core/outputplugin.cpp include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/abstractmodule.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/pluginconnectorplain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outputplugin.o core/outputplugin.cpp

plot2d.o: core/plot2d.cpp include/plot2d.h \
		include/samdsp.h \
		include/samqvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plot2d.o core/plot2d.cpp

pluginconnector.o: core/pluginconnector.cpp include/pluginconnector.h \
		include/abstractplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pluginconnector.o core/pluginconnector.cpp

pluginmanager.o: core/pluginmanager.cpp include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/abstractmodule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pluginmanager.o core/pluginmanager.cpp

pluginthread.o: core/pluginthread.cpp include/pluginthread.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/runmanager.h \
		include/eventbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pluginthread.o core/pluginthread.cpp

remotecontrolpanel.o: core/remotecontrolpanel.cpp include/remotecontrolpanel.h \
		include/geckoremote.h \
		include/runmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o remotecontrolpanel.o core/remotecontrolpanel.cpp

runmanager.o: core/runmanager.cpp include/runmanager.h \
		include/scopemainwindow.h \
		include/runthread.h \
		include/pluginthread.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/abstractinterface.h \
		include/geckoremote.h \
		include/interfacemanager.h \
		include/abstractmodule.h \
		include/systeminfo.h \
		include/eventbuffer.h \
		include/outputplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runmanager.o core/runmanager.cpp

runthread.o: core/runthread.cpp include/runthread.h \
		include/abstractmodule.h \
		include/modulemanager.h \
		include/interfacemanager.h \
		include/runmanager.h \
		include/abstractinterface.h \
		include/eventbuffer.h \
		include/pluginconnector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runthread.o core/runthread.cpp

scopemainwindow.o: core/scopemainwindow.cpp include/scopemainwindow.h \
		include/runthread.h \
		include/pluginthread.h \
		include/pluginmanager.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/abstractinterface.h \
		include/geckoremote.h \
		include/addeditdlgs.h \
		include/abstractmodule.h \
		include/interfacemanager.h \
		include/hexspinbox.h \
		include/baseui.h \
		include/systeminfo.h \
		include/remotecontrolpanel.h \
		include/outputplugin.h \
		include/eventbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scopemainwindow.o core/scopemainwindow.cpp

threadbuffer.o: core/threadbuffer.cpp include/threadbuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o threadbuffer.o core/threadbuffer.cpp

viewport.o: core/viewport.cpp include/viewport.h \
		include/confmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewport.o core/viewport.cpp

sis3100module.o: interface/sis3100module.cpp interface/sis3100module.h \
		lib/sis3100_calls/sis3100_vme_calls.h \
		include/baseinterface.h \
		include/abstractinterface.h \
		interface/sis3100ui.h \
		include/baseui.h \
		include/interfacemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sis3100module.o interface/sis3100module.cpp

sis3100ui.o: interface/sis3100ui.cpp interface/sis3100ui.h \
		interface/sis3100module.h \
		lib/sis3100_calls/sis3100_vme_calls.h \
		include/baseinterface.h \
		include/abstractinterface.h \
		include/baseui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sis3100ui.o interface/sis3100ui.cpp

caen792module.o: module/caen792module.cpp module/caen792module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/caenadcdmx.h \
		module/caen_v785.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		module/caen_v792.h \
		module/caen792ui.h \
		include/hexspinbox.h \
		include/baseui.h \
		include/confmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caen792module.o module/caen792module.cpp

caen792ui.o: module/caen792ui.cpp module/caen792ui.h \
		include/hexspinbox.h \
		include/baseui.h \
		module/caen792module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/caenadcdmx.h \
		module/caen_v785.h \
		include/pluginmanager.h \
		include/modulemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caen792ui.o module/caen792ui.cpp

caenadcdmx.o: module/caenadcdmx.cpp module/caenadcdmx.h \
		module/caen_v785.h \
		include/eventbuffer.h \
		include/pluginconnector.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caenadcdmx.o module/caenadcdmx.cpp

fanoutplugin.o: plugin/aux/fanoutplugin.cpp plugin/aux/fanoutplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/pluginconnectorqueued.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fanoutplugin.o plugin/aux/fanoutplugin.cpp

inttodoubleplugin.o: plugin/aux/inttodoubleplugin.cpp plugin/aux/inttodoubleplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/pluginconnectorqueued.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inttodoubleplugin.o plugin/aux/inttodoubleplugin.cpp

pulsing.o: plugin/aux/pulsing.cpp plugin/aux/pulsing.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/abstractinterface.h \
		include/abstractmodule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pulsing.o plugin/aux/pulsing.cpp

multiplecachehistogramplugin.o: plugin/cache/multiplecachehistogramplugin.cpp plugin/cache/multiplecachehistogramplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginconnectorqueued.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/plot2d.h \
		include/samdsp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multiplecachehistogramplugin.o plugin/cache/multiplecachehistogramplugin.cpp

eventbuilderBIGROOTplugin.o: plugin/pack/eventbuilderBIGROOTplugin.cpp plugin/pack/eventbuilderBIGROOTplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/pluginmanager.h \
		include/pluginconnectorqueued.h \
		/snap/root-framework/943/usr/local/include/TFile.h \
		/snap/root-framework/943/usr/local/include/Compression.h \
		/snap/root-framework/943/usr/local/include/RtypesCore.h \
		/snap/root-framework/943/usr/local/include/ROOT/RConfig.hxx \
		/snap/root-framework/943/usr/local/include/RVersion.h \
		/snap/root-framework/943/usr/local/include/ROOT/RVersion.hxx \
		/snap/root-framework/943/usr/local/include/RConfigure.h \
		/snap/root-framework/943/usr/local/include/DllImport.h \
		/snap/root-framework/943/usr/local/include/TDirectoryFile.h \
		/snap/root-framework/943/usr/local/include/TDirectory.h \
		/snap/root-framework/943/usr/local/include/TNamed.h \
		/snap/root-framework/943/usr/local/include/TObject.h \
		/snap/root-framework/943/usr/local/include/Rtypes.h \
		/snap/root-framework/943/usr/local/include/strtok.h \
		/snap/root-framework/943/usr/local/include/strlcpy.h \
		/snap/root-framework/943/usr/local/include/snprintf.h \
		/snap/root-framework/943/usr/local/include/TGenericClassInfo.h \
		/snap/root-framework/943/usr/local/include/TSchemaHelper.h \
		/snap/root-framework/943/usr/local/include/TIsAProxy.h \
		/snap/root-framework/943/usr/local/include/TVirtualIsAProxy.h \
		/snap/root-framework/943/usr/local/include/TStorage.h \
		/snap/root-framework/943/usr/local/include/TVersionCheck.h \
		/snap/root-framework/943/usr/local/include/TString.h \
		/snap/root-framework/943/usr/local/include/TMathBase.h \
		/snap/root-framework/943/usr/local/include/ROOT/TypeTraits.hxx \
		/snap/root-framework/943/usr/local/include/TClass.h \
		/snap/root-framework/943/usr/local/include/TDictionary.h \
		/snap/root-framework/943/usr/local/include/ESTLType.h \
		/snap/root-framework/943/usr/local/include/TObjArray.h \
		/snap/root-framework/943/usr/local/include/TSeqCollection.h \
		/snap/root-framework/943/usr/local/include/TCollection.h \
		/snap/root-framework/943/usr/local/include/TIterator.h \
		/snap/root-framework/943/usr/local/include/TVirtualRWMutex.h \
		/snap/root-framework/943/usr/local/include/TVirtualMutex.h \
		/snap/root-framework/943/usr/local/include/ROOT/RRangeCast.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/RSpan.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/span.hxx \
		/snap/root-framework/943/usr/local/include/TUUID.h \
		/snap/root-framework/943/usr/local/include/TList.h \
		/snap/root-framework/943/usr/local/include/TBuffer.h \
		/snap/root-framework/943/usr/local/include/TDataType.h \
		/snap/root-framework/943/usr/local/include/Bytes.h \
		/snap/root-framework/943/usr/local/include/Byteswap.h \
		/snap/root-framework/943/usr/local/include/TDatime.h \
		/snap/root-framework/943/usr/local/include/TUrl.h \
		/snap/root-framework/943/usr/local/include/ROOT/RConcurrentHashColl.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/TRWSpinLock.hxx \
		/snap/root-framework/943/usr/local/include/ROOT/TSpinMutex.hxx \
		/snap/root-framework/943/usr/local/include/TTree.h \
		/snap/root-framework/943/usr/local/include/ROOT/TIOFeatures.hxx \
		/snap/root-framework/943/usr/local/include/TArrayD.h \
		/snap/root-framework/943/usr/local/include/TArray.h \
		/snap/root-framework/943/usr/local/include/TArrayI.h \
		/snap/root-framework/943/usr/local/include/TAttFill.h \
		/snap/root-framework/943/usr/local/include/TAttLine.h \
		/snap/root-framework/943/usr/local/include/TAttMarker.h \
		/snap/root-framework/943/usr/local/include/TVirtualTreePlayer.h \
		/snap/root-framework/943/usr/local/include/TBranch.h \
		/snap/root-framework/943/usr/local/include/TBranchCacheInfo.h \
		/snap/root-framework/943/usr/local/include/TBits.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventbuilderBIGROOTplugin.o plugin/pack/eventbuilderBIGROOTplugin.cpp

eventbuilderBIGplugin.o: plugin/pack/eventbuilderBIGplugin.cpp plugin/pack/eventbuilderBIGplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/pluginmanager.h \
		include/pluginconnectorqueued.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventbuilderBIGplugin.o plugin/pack/eventbuilderBIGplugin.cpp

mtdc32Processor.o: plugin/processing/mtdc32Processor.cpp plugin/processing/mtdc32Processor.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		module/mesytec_mtdc_32_v2.h \
		include/pluginmanager.h \
		include/pluginconnectorqueued.h \
		include/runmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mtdc32Processor.o plugin/processing/mtdc32Processor.cpp

madc32Processor.o: plugin/processing/madc32Processor.cpp plugin/processing/madc32Processor.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/modulemanager.h \
		module/mesytec_madc_32_v2.h \
		include/pluginmanager.h \
		include/pluginconnectorqueued.h \
		include/runmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o madc32Processor.o plugin/processing/madc32Processor.cpp

mesytecMadc32ui.o: module/mesytecMadc32ui.cpp module/mesytecMadc32ui.h \
		include/plot2d.h \
		include/samdsp.h \
		include/hexspinbox.h \
		include/geckoui.h \
		module/mesytec_madc_32_v2.h \
		include/baseui.h \
		module/mesytecMadc32module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/mesytecMadc32dmx.h \
		include/pluginmanager.h \
		include/modulemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesytecMadc32ui.o module/mesytecMadc32ui.cpp

mesytecMadc32module.o: module/mesytecMadc32module.cpp module/mesytecMadc32module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/mesytecMadc32dmx.h \
		module/mesytec_madc_32_v2.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		module/mesytecMadc32ui.h \
		include/plot2d.h \
		include/samdsp.h \
		include/hexspinbox.h \
		include/geckoui.h \
		include/baseui.h \
		include/confmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesytecMadc32module.o module/mesytecMadc32module.cpp

mesytecMadc32dmx.o: module/mesytecMadc32dmx.cpp module/mesytecMadc32dmx.h \
		module/mesytec_madc_32_v2.h \
		include/eventbuffer.h \
		include/pluginconnector.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesytecMadc32dmx.o module/mesytecMadc32dmx.cpp

mesytecMtdc32ui.o: module/mesytecMtdc32ui.cpp module/mesytecMtdc32ui.h \
		include/plot2d.h \
		include/samdsp.h \
		include/hexspinbox.h \
		include/geckoui.h \
		module/mesytec_mtdc_32_v2.h \
		include/baseui.h \
		module/mesytecMtdc32module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/mesytecMtdc32dmx.h \
		include/pluginmanager.h \
		include/modulemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesytecMtdc32ui.o module/mesytecMtdc32ui.cpp

mesytecMtdc32module.o: module/mesytecMtdc32module.cpp module/mesytecMtdc32module.h \
		include/basemodule.h \
		include/abstractmodule.h \
		include/abstractinterface.h \
		include/pluginconnector.h \
		include/runmanager.h \
		include/eventbuffer.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		module/mesytecMtdc32dmx.h \
		module/mesytec_mtdc_32_v2.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		module/mesytecMtdc32ui.h \
		include/plot2d.h \
		include/samdsp.h \
		include/hexspinbox.h \
		include/geckoui.h \
		include/baseui.h \
		include/confmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesytecMtdc32module.o module/mesytecMtdc32module.cpp

mesytecMtdc32dmx.o: module/mesytecMtdc32dmx.cpp module/mesytecMtdc32dmx.h \
		module/mesytec_mtdc_32_v2.h \
		include/eventbuffer.h \
		include/pluginconnector.h \
		include/abstractmodule.h \
		include/outputplugin.h \
		include/baseplugin.h \
		include/abstractplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesytecMtdc32dmx.o module/mesytecMtdc32dmx.cpp

MatrixPlotWalk.o: plugin/cache/MatrixPlotWalk.cpp plugin/cache/MatrixPlotWalk.h \
		include/2Ddisplay.h \
		include/baseplugin.h \
		include/abstractplugin.h \
		include/pluginconnector.h \
		include/pluginmanager.h \
		include/modulemanager.h \
		include/runmanager.h \
		include/pluginconnectorqueued.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MatrixPlotWalk.o plugin/cache/MatrixPlotWalk.cpp

moc_addeditdlgs.o: moc_addeditdlgs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addeditdlgs.o moc_addeditdlgs.cpp

moc_geckoremote.o: moc_geckoremote.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_geckoremote.o moc_geckoremote.cpp

moc_pluginthread.o: moc_pluginthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pluginthread.o moc_pluginthread.cpp

moc_remotecontrolpanel.o: moc_remotecontrolpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_remotecontrolpanel.o moc_remotecontrolpanel.cpp

moc_runthread.o: moc_runthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runthread.o moc_runthread.cpp

moc_scopemainwindow.o: moc_scopemainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scopemainwindow.o moc_scopemainwindow.cpp

moc_systeminfo.o: moc_systeminfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systeminfo.o moc_systeminfo.cpp

moc_threadbuffer.o: moc_threadbuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_threadbuffer.o moc_threadbuffer.cpp

moc_abstractmodule.o: moc_abstractmodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_abstractmodule.o moc_abstractmodule.cpp

moc_abstractplugin.o: moc_abstractplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_abstractplugin.o moc_abstractplugin.cpp

moc_basemodule.o: moc_basemodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basemodule.o moc_basemodule.cpp

moc_baseplugin.o: moc_baseplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_baseplugin.o moc_baseplugin.cpp

moc_geckoui.o: moc_geckoui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_geckoui.o moc_geckoui.cpp

moc_interfacemanager.o: moc_interfacemanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_interfacemanager.o moc_interfacemanager.cpp

moc_modulemanager.o: moc_modulemanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modulemanager.o moc_modulemanager.cpp

moc_outputplugin.o: moc_outputplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_outputplugin.o moc_outputplugin.cpp

moc_plot2d.o: moc_plot2d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plot2d.o moc_plot2d.cpp

moc_pluginmanager.o: moc_pluginmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pluginmanager.o moc_pluginmanager.cpp

moc_runmanager.o: moc_runmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runmanager.o moc_runmanager.cpp

moc_sis3100module.o: moc_sis3100module.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sis3100module.o moc_sis3100module.cpp

moc_sis3100ui.o: moc_sis3100ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sis3100ui.o moc_sis3100ui.cpp

moc_caen792module.o: moc_caen792module.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_caen792module.o moc_caen792module.cpp

moc_caen792ui.o: moc_caen792ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_caen792ui.o moc_caen792ui.cpp

moc_inttodoubleplugin.o: moc_inttodoubleplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inttodoubleplugin.o moc_inttodoubleplugin.cpp

moc_pulsing.o: moc_pulsing.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pulsing.o moc_pulsing.cpp

moc_multiplecachehistogramplugin.o: moc_multiplecachehistogramplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multiplecachehistogramplugin.o moc_multiplecachehistogramplugin.cpp

moc_eventbuilderBIGROOTplugin.o: moc_eventbuilderBIGROOTplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventbuilderBIGROOTplugin.o moc_eventbuilderBIGROOTplugin.cpp

moc_eventbuilderBIGplugin.o: moc_eventbuilderBIGplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventbuilderBIGplugin.o moc_eventbuilderBIGplugin.cpp

moc_mtdc32Processor.o: moc_mtdc32Processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mtdc32Processor.o moc_mtdc32Processor.cpp

moc_madc32Processor.o: moc_madc32Processor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_madc32Processor.o moc_madc32Processor.cpp

moc_mesytecMadc32module.o: moc_mesytecMadc32module.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mesytecMadc32module.o moc_mesytecMadc32module.cpp

moc_mesytecMadc32ui.o: moc_mesytecMadc32ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mesytecMadc32ui.o moc_mesytecMadc32ui.cpp

moc_mesytecMtdc32module.o: moc_mesytecMtdc32module.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mesytecMtdc32module.o moc_mesytecMtdc32module.cpp

moc_mesytecMtdc32ui.o: moc_mesytecMtdc32ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mesytecMtdc32ui.o moc_mesytecMtdc32ui.cpp

moc_MatrixPlotWalk.o: moc_MatrixPlotWalk.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MatrixPlotWalk.o moc_MatrixPlotWalk.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

